In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
word_to_idx = {"I": 0, "love": 1, "eating": 2, "and": 3, "sleeping": 4}
embeddings = nn.Embedding(5,7) # 5 words in vocab, embedding size is 7
word_index = torch.tensor(word_to_idx["love"])
print(word_index)

tensor(1)


In [4]:
love = embeddings(word_index)
print(love)
print(love.shape)

tensor([-0.2887, -1.2974,  1.1971,  1.0400,  0.2099,  0.4339,  2.2324],
       grad_fn=<EmbeddingBackward0>)
torch.Size([7])


In [6]:
all_ind = torch.tensor([w for w in range(5)], dtype = torch.long)
all_words = embeddings(all_ind)
print(all_ind)
print(all_words)
print(all_words.shape)

tensor([0, 1, 2, 3, 4])
tensor([[ 0.6054, -1.5928, -1.6199, -0.6544, -0.9149,  1.3558,  0.0747],
        [-0.2887, -1.2974,  1.1971,  1.0400,  0.2099,  0.4339,  2.2324],
        [-0.6239, -0.8104, -0.6596,  0.1033, -0.7934,  0.0460, -1.1173],
        [-0.8125,  0.4852, -1.1718,  1.3177, -1.2259,  0.2414, -0.4878],
        [ 0.2467, -0.9847, -2.1208,  0.0981,  0.9216, -1.0878, -1.1428]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([5, 7])


In [7]:
# Try N-Gram skip model for word embeddings. 