In [1]:
import torch
import torch.nn.functional as F

In [4]:
# o/ps before softmax
preds = torch.log(torch.rand(3))
preds

tensor([-1.0921, -1.0034, -0.5146])

In [7]:
# regular softmax
F.softmax(preds, dim=-1)

tensor([0.2581, 0.2820, 0.4598])

In [10]:
# applying temperature
temp = 0.5

F.softmax(preds/temp, dim = -1)
# Here we can see that the highest confidence from before became higher and others lower. Sharper distribution. 
# High confidence as the temp lower (temp < 1)

tensor([0.1863, 0.2224, 0.5913])

In [13]:
temp = 10
F.softmax(preds/temp, dim = -1)

# Almost a uniform distribution. The model has no confidence in any classification. 
# Low confidence as the temp higher (temp > 1)

tensor([0.3259, 0.3288, 0.3453])